server/jest.config.js

테스트를 위해서 jest config file 설정
파일누락

[Add] 테스트를 위해서 jest config file 설정

---

client/package.json
client/src/App.test.tsx
client/src/composition/Feed/Comment.tsx
client/src/composition/Feed/FeedBody.tsx
client/src/composition/Feed/FeedHeader.tsx
client/src/composition/Feed/index.tsx
client/src/hooks/useIntersectObserver.tsx
server/src/api/feed/feed.resolvers.ts
server/src/schema/commonTypes.ts
server/src/schema/feed/query.ts

- infinite scroll insepctobserver 로 구현
- hook으로 분리
- 코드리뷰 받은사항 수정해서 반영
- 불필요한 fragment 삭제
- 쿼리 네임스페이스 변경 
- 매직넘버 상수분리
- component key값 지정
- 파라미터 타입지정
- 인터페이스 분리 
- 프로필 공통 컴포넌트 사용하도록 수정 
- 비동기로 스크롤 이벤트를 감지하여 동작하도록 설정

Feature 32/infinite scroll

---

.gitignore
client/.gitignore
client/package.json
client/src/apollo/ApolloClient.ts
client/src/pages/SignUp/SignUpContainer.tsx
server/package.json
server/src/api/signUp/signUp.resolvers.ts
server/src/app.ts
server/src/db.ts
server/src/errors/EmailAlreadyExistsError.ts
server/src/errors/createDBError.ts
server/src/init.ts
server/src/middleware/authController.ts
server/src/middleware/passport.ts
server/src/middleware/setUserFromJWT.ts
server/src/middleware/uploadToObjStorage.ts
server/src/utils/config.ts
server/src/utils/jwt.ts
server/src/utils/parseDB.ts
server/src/utils/requestDB.ts
server/test/api/image/uploadImage.test.ts
server/test/api/signUp/signUp.query.ts
server/test/api/signUp/signUp.test.ts
server/test/utils.ts

회원가입 api를 개선하였다.
- 이메일 중복 체크 기능 추가
- 회원가입시 jwt토큰을 생성하여 cookie에 넣어주는 기능 추가
- 관련된 cors 문제 해결
- 반복되는 env 처리 작업을 모듈로 따로 분리
(기능 순서에 따라)
- api를 탈취해서 회원을 중복 생성할 가능성이 있으므로, 중복 체크를 하여 apollo-errors를 이용해 에러를 던진다.
- 자동로그인을 위해 회원가입시 쿠키에 토큰을 넣어준다. 클라이언트는 이를 인지해 응답이 올바를 경우 자동으로 메인 페이지로 이동한다.
- 클라이언트에서 credentials: 'include' 설정을 하면 cors 문제가 생겼다. 자세한 것은 추후에 공부 예정
- 한 환경변수에 대해 NODE_ENV가 prd인지 dev인지에 따라 분기하는 작업이 많아져서 이를 모듈로 작성하여 중복을 없애고자 하였다.

Feature 81/signup api

---

client/package.json
client/src/apollo/ApolloClient.ts
client/src/apollo/Link.ts
client/src/cache/client.gql.tsx
client/src/pages/Routes/LoginRoutes.tsx
client/src/resolvers.ts

- link의 용도별 분기문 처리
- 로그인/로그아웃 기능

Feature 82/routing

---

client/src/composition/Feed/WritingFeed/WritingFeedContainer.tsx
server/src/api/feed/feed.resolvers.ts

- 버그 수정
- useEffect 이용하여 처음 렌더링 될 때만 커서가 맨 뒤로 가게 함.
- requestDB async function 이므로 try catch 로 감쌌음

[Fix] WritingFeed 렌더할 때 textarea로 커서 가는 것 수정, requestDB try catch로 감싸기

---

client/package.json
client/src/apollo/ApolloClient.tsx
client/src/apollo/resolvers.ts
client/src/composition/Feed/FeedBody.tsx
client/src/composition/Feed/index.tsx
client/src/composition/Search/CardContainer.tsx
client/src/index.tsx

- 피드 보여줄 때 버그 수정( 글씨가 피드 크기를 넘어가는 버그, 줄바꿈이 안 먹히는 버그)
- persist-cache 제거 및 fetchpolicy 수정
피드 쓰기 내용을 캐싱하는 과정에서 persist-cache를 이용하는 것이 다른 기능에 영향을 많이 끼쳐
없애는 것이 좋다고 판단.
피드 쓰기 내용은 localStorage에 저장하여 캐싱

Feature 58/header messenger frontend

---

client/src/composition/Feed/Feed.tsx
client/src/composition/Feed/FeedComment/CommentPresentor.tsx
client/src/composition/Feed/FeedComment/WriteCommentPresentor.tsx
client/src/composition/Feed/feed.query.tsx
client/src/composition/Feed/index.tsx
client/src/hooks/useInput.ts
server/src/api/feed/feed.graphql
server/src/api/feed/feed.resolvers.ts
server/src/schema/feed/query.ts

Feature 10/add comment

---

client/src/composition/Feed/FeedComment/WriteCommentPresentor.tsx
client/src/composition/Feed/WritingFeed/WritingFeedContainer.tsx
client/src/composition/Feed/WritingFeed/WritingPresenter.tsx

- 피드 쓰기 사진 업로드 시 image validate
#161

[Bug] 피드 쓰기 사진 업로드 시 image validate

---

client/src/components/Button.tsx
client/src/composition/Feed/FeedComment/WriteCommentPresentor.tsx

- 댓글 입력되지 않는 부분 수정 
- 댓글 입력 시 프로필 이미지와 닉네임 매칭 안되던 부분 수정 
이슈 : https://github.com/connect-foundation/2019-17/issues/10

[Bug] Feature 10/add comment bug fix

---

client/src/composition/Feed/WritingFeed/WritingFeedContainer.tsx
client/src/composition/Feed/WritingFeed/WritingPresenter.tsx

- 피드 쓰기 다중 클릭시 여러개 등록되는 버그 수정
- 피드 글자수 제한
#155 #162

Feature 155/feed enroll bug

---

client/src/composition/Header/Alarm/feedAlarm.tsx
client/src/composition/Header/AlarmTab.tsx
server/src/api/feed/feed.graphql
server/src/api/feed/feed.resolvers.ts
server/src/schema/feed/query.ts
server/src/utils/parseData.ts

- 피드 등록시 알람 연결 생성하도록  api 수정
- 알람목록 가지고오는 api 작성
알림기능 작업 : https://github.com/connect-foundation/2019-17/issues/57
- 알림이 없으면 빈 배열이 온다.

Feature 57/feed alarm

---

server/src/api/feed/feed.graphql
server/src/api/feed/feed.resolvers.ts
server/src/schema/feed/query.ts

피드 알림 1개 읽은상태 변경 api
피드 알림 모두에 대한 읽음상태 변경 api
피드 알림을 클릭했을 때 상태를 변경하기 위해서 
지금은 feed 알림에 대한 처리만 가능
토글이 아닌 true 로만 변경

Feature 56/change read state api

---

client/src/composition/Feed/Feed.tsx
client/src/composition/Feed/FeedFooter.tsx
client/src/composition/Feed/NoFeed.tsx
client/src/composition/Feed/index.tsx
client/src/pages/SignUp/SignUpContainer.tsx
client/src/utils/dateUtil.ts
server/src/api/feed/feed.resolvers.ts

- 날짜 한국시간에 맞게 수정
- 정규식 수정
- 마지막 피드 서버에러 수정 및 컴포넌트 수정
- 친구 없을 때 피드 등록 안되는 버그 수정
- 마지막 피드 무한패칭 에러 수정

[BUGFIX] 32/infinite scroll bugfix

---

client/src/components/Profile.tsx
client/src/components/UserCard.tsx
client/src/composition/ChatRooms/ChatRoom.tsx
client/src/composition/Feed/Feed.tsx
client/src/composition/Feed/FeedComment/CommentPresentor.tsx
client/src/composition/Feed/FeedComment/WriteCommentPresentor.tsx
client/src/composition/Header/MessageTab/MessageTabContainer.tsx
client/src/composition/Header/index.tsx
client/src/constants.ts

[Fix] DEFAULT.PFOFILE .png -> .jpg

---

client/src/composition/Feed/FeedComment/CommentPresentor.tsx

- feed 보다 comment가 더 길어지는 경우 수정

[Bug] comment feed 넘어감 bugfix

---

client/src/apollo/ApolloClient.tsx
client/src/apollo/Link.ts
client/src/apollo/resolvers.ts
client/src/apollo/typeDefs.ts
client/src/cache/auth.query.ts
client/src/cache/writingFeed.query.ts
client/src/components/ActionButton.tsx
client/src/components/Button.tsx
client/src/components/FriendProfile.tsx
client/src/components/Helmet/index.tsx
client/src/components/Icon/BoostBookLogo.tsx
client/src/components/Icon/RoundThumbIcon.tsx
client/src/components/Icon/SearchButtonIcon.tsx
client/src/components/Icon/ThumbLikeIcon.tsx
client/src/components/Loader.tsx
client/src/components/User.tsx
client/src/components/UserCard.tsx
client/src/composition/Feed/WritingFeed/WritingFeedContainer.tsx
client/src/composition/Header/index.tsx
client/src/composition/Search/ButtonContainer.tsx
client/src/composition/Search/SearchBox.tsx
client/src/constants.ts
client/src/pages/Routes/AuthRoutes.tsx
client/src/pages/Routes/LoginRoutes.tsx
client/tsconfig.json

Feature 209/refactor pair

---

client/src/composition/DetailFeed/CommonModal.tsx
client/src/composition/DetailFeed/index.tsx
client/src/composition/Header/AlarmTab/AlarmBox.tsx
server/src/api/feed/feed.resolvers.ts
server/src/schema/feed/query.ts

- 코드리뷰 사항 수정 
- publish 된 댓글 알림에 대해서도 상세페이지가 뜨도록 수정 
- 가독성을 높이는 방향으로 코드리뷰 반영 
- 댓글의 경우 발행된 id 가 comment의 id 값이였어서 뜨지 않았던 것으로 연결된 feedId 가 뜨도록 수정

Feature 167/review refactor

---

client/src/composition/Feed/index.tsx
client/src/composition/FriendList/index.tsx
client/src/composition/Header/AlarmTab/AlarmBox.tsx
client/src/utils/dateUtil.ts
server/src/api/feed/feed.graphql

- 날짜 포맷에 맞게 수정
- 리펙토링
- 변수명 일부 수정 , Feed.tsx 코드 정리

Feature 157/timezone bugfix

---

server/src/api/chat/chat.mutation.ts
server/src/api/chat/chat.pubsub.ts
server/src/api/chat/chatRoom.mutation.ts

- createChatAndPublish function 분리

[Fix] createChatAndPublish function 분리

---

client/src/composition/Header/AlarmTab/NewFeedAlarmNum.tsx
client/src/composition/Header/HeaderTab.tsx

Feature 175/alarm red dot

---

client/package.json
client/src/composition/DetailFeed/CommonModal.tsx
client/src/composition/DetailFeed/index.tsx
client/src/composition/Feed/Image.tsx
client/src/composition/Feed/ImageContainer.tsx
client/src/composition/Feed/index.tsx
client/src/composition/Header/CommonBox.tsx
client/src/style/carousel.css

- feed carousel 모듈로 추가
- styled component 적용이 되지 않아서  스타일 커스텀을 위해 css 추가
- 이미지 케로셀 모달에에서 보여지게 처리
- 케로셀 목록은 내부 목록이 component분리이 안됨...

Feature 32/performance check
